version: '3'

services:
  app:
    container_name: docker-pyspark-mongo
    build: .
    external_links:
      - mongo
    networks:
      - connector
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - connector

networks:
  connector: